### ISSUE TITLE
A problem occurred starting process 'command 'eslint''

### ISSUE THREAD

**Issue by potolok1986** [scobal/gradle-eslint-plugin#1]
I can not run the plugin . Errors occur frequently when you start gradle eslint
A problem occurred starting process 'command 'eslint''
Here are the contents of build.gradle
plugins {
  id "com.github.scobal.eslint" version "1.0.1"
}
eslint {    
    config = ".eslintrc.json"
    inputs = ["js/*.js*"]
}

**Comment by kanikashah90** [comment]
I am also having the same issues. Can't execute the command 'gradle eslint'. I get the following error: Process 'command 'eslint'' finished with exit value -1 (state: FAILED)

Looking at the code it looks like ESLintPluginConvention.groovy is missing the method  'getExecutable()' being called here in the eslint task:
https://github.com/scobal/gradle-eslint-plugin/blob/master/src/main/groovy/com/github/scobal/eslint/ESLintPlugin.groovy#L29

**Comment by g-gabber** [comment]
I have the same problem

**Comment by scobal** [comment]
This should now be fixed in 1.0.2 after this PR: 

https://github.com/scobal/gradle-eslint-plugin/pull/3 

and consequently this commit: ebe7112

I haven't been able to test this on Windows so let me know if there are any issues

**Comment by prasanthchitturi** [comment]
Hi,

I am having the same issue. Any solution for this?
