### ISSUE TITLE
Plugin does not enable setting all eslint options

### ISSUE THREAD

**Issue by juchnowska** [scobal/gradle-eslint-plugin#2]
The only options that are available to configure are listed here: https://github.com/scobal/gradle-eslint-plugin#configuration. Eslint command line interface allows setting more options which are helpful (i.e. the output file). It would be nice if all eslint parameters could be configurable in the plugin (by introducing handling more options or at least enable passing any option in the form of key=value string).

**Comment by scobal** [comment]
Thanks for opening this issue 👍  

Support for `--output-file` and `--format` have just been added and I'd like to add more (and certainly will accept pull requests that add more :) ).

I'd like to avoid adding an override in the form of key=value string in favour of adding the specific command line options as configuration on the plugin.
